name: Auto Close Issues

on:
  issues:
    types: [labeled]

jobs:
  auto-close-completed:
    if: github.event.label.name == 'completed' || github.event.label.name == 'wontfix'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Close issue
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed'
            })